#!/bin/bash

# Set up the .bashrc with the alias
#: <<'COMMENT'
echo "alias python='python3'" >> /home/pi/.bashrc
echo "alias pip='pip3'"       >> /home/pi/.bashrc

# Set up .bash_profile in case they ssh into the pi
cat >> /home/pi/.bash_profile <<-EOMESSAGE
if [ -f ~/.bashrc ]; then
     source \$HOME/.bashrc
fi
EOMESSAGE
chown pi /home/pi/.bash_profile

echo "Setting up PI to email you on boot."
apt-get update
apt-get install -y msmtp msmtp-mta
apt-get install -y mailutils
#COMMENT

echo "Enter the email you wish to use, two email addresses if two people get the email: "
read email_address
echo $email_address

echo "Password Jim gave you for gmail specail user account: "
read email_password

read -r -d '\n' fileout <<EMAIL_CONFIG
#Generics
defaults
auth     on
tls      on

tls_trust_file /etc/ssl/certs/ca-certificates.crt
# log location
logfile     ~/.msmtp.log

#gmail
account     gmail
host        smtp.gmail.com
port        587

from        root@raspi-buster
user        ese205smtp@gmail.com
password    $email_password 

account default : gmail
EMAIL_CONFIG

echo "$fileout" >> /etc/msmtprc 

echo "Creating the script to email with the 30 second delay."

read -r -d '\n' fileout <<EMAIL_CONFIG
#!/bin/bash
sleep 30
hostname -I | mail -s "RasPi IP" $email_address
EMAIL_CONFIG

echo "$fileout" >> /usr/local/bin/emailer.sh
chmod 755 /usr/local/bin/emailer.sh

read -r -d '\n' fileout <<EMAIL_CONFIG
# DO NOT EDIT THIS FILE - edit the master and reinstall.
# (/tmp/crontab.OchAOl/crontab installed on Sun Nov 17 12:33:42 2019)
# (Cron version -- \$Id: crontab.c,v 2.13 1994/01/17 03:20:37 vixie Exp $)
# Edit this file to introduce tasks to be run by cron.
# 
# Each task to run has to be defined through a single line
# indicating with different fields when the task will be run
# and what command to run for the task
# 
# To define the time you can provide concrete values for
# minute (m), hour (h), day of month (dom), month (mon),
# and day of week (dow) or use '*' in these fields (for 'any').
# 
# Notice that tasks will be started based on the cron's system
# daemon's notion of time and timezones.
# 
# Output of the crontab jobs (including errors) is sent through
# email to the user the crontab file belongs to (unless redirected).
# 
# For example, you can run a backup of all your user accounts
# at 5 a.m every week with:
# 0 5 * * 1 tar -zcf /var/backups/home.tgz /home/
# 
# For more information see the manual pages of crontab(5) and cron(8)
# 
# m h  dom mon dow   command

@reboot /usr/local/bin/emailer.sh
EMAIL_CONFIG

echo "$fileout" >> /var/spool/cron/crontabs/pi
chmod 600 /var/spool/cron/crontabs/pi
chown pi  /var/spool/cron/crontabs/pi
chgrp crontab /var/spool/cron/crontabs/pi
